---
# tasks file for sssd

- name: Install SSSD and related packages
  yum:
    name: awscli
    state: installed
  tags:
    - install

#- name: Start and enable the sssd service
#  service:
#    name: sssd
#    enabled: yes
#    state: started